# kamikaze_komodo/core/enums.py

from enum import Enum


class OrderType(Enum):

    """

    Represents the type of an order.

    """

    MARKET = "market"

    LIMIT = "limit"

    STOP = "stop"

    STOP_LIMIT = "stop_limit"

    TAKE_PROFIT = "take_profit"

    TAKE_PROFIT_LIMIT = "take_profit_limit"


class OrderSide(Enum):

    """

    Represents the side of an order.

    """

    BUY = "buy"

    SELL = "sell"


class SignalType(Enum):

    """

    Represents the type of trading signal generated by a strategy.

    """

    LONG = "LONG"

    SHORT = "SHORT"

    HOLD = "HOLD"

    CLOSE_LONG = "CLOSE_LONG"

    CLOSE_SHORT = "CLOSE_SHORT"


class CandleInterval(Enum):

    """

    Represents common candle intervals for market data.

    Follows CCXT conventions where possible.

    """

    ONE_MINUTE = "1m"

    THREE_MINUTES = "3m"

    FIVE_MINUTES = "5m"

    FIFTEEN_MINUTES = "15m"

    THIRTY_MINUTES = "30m"

    ONE_HOUR = "1h"

    TWO_HOURS = "2h"

    FOUR_HOURS = "4h"

    SIX_HOURS = "6h"

    EIGHT_HOURS = "8h"

    TWELVE_HOURS = "12h"

    ONE_DAY = "1d"

    THREE_DAYS = "3d"

    ONE_WEEK = "1w"

    ONE_MONTH = "1M"


class TradeResult(Enum):

    """

    Represents the outcome of a trade.

    """

    WIN = "WIN"

    LOSS = "LOSS"

    BREAKEVEN = "BREAKEVEN"
